---
title: "Bolsa familia"
author: "Erick Nasareth"
date: "2025-04-20"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load("tidyverse", "readxl", "knitr")

```


```{r}

bolsa <- read_xlsx("Data/bolsa_familia_consolidado_geral_2023.xlsx")
populacao <- read_xls("Data/pop_cadastrada_2023.xls")
#atendimento <- read_xlsx("Data/atendimento_saude_2023.xlsx")
#palestras <- read_xlsx("Data/palestras_municipio_2023.xlsx") #temas
praticas <- read_xlsx("Data/praticas2023.xlsx")

```


```{r}

bolsa <- rename(bolsa, Ibge = IBGE)
populacao <- rename(populacao, Ibge = IBGE)

```

```{r}
names(populacao)[7] <- "populacao_cadastrada"
```


```{r}
populacao <- populacao %>%
  select(Ibge, populacao_cadastrada, Região)

names(populacao)[2] <- "População"
```



```{r}
bolsa <- bolsa %>%
  mutate(Mun_uf = str_c(bolsa$Município, " (", bolsa$Estado, ")"))
```



```{r}
bolsa_municipio <- bolsa %>%
  select(Estado, Município, Ibge, `Qtd. beneficiários a serem acompanhados`, `Qtd. beneficiários acompanhados`, `Perc. cobertura de beneficiários acompanhados (%)`, Mun_uf)

bolsa_estado <- bolsa %>%
  select(Estado, Município, Ibge, `Qtd. beneficiários a serem acompanhados`, `Qtd. beneficiários acompanhados`)

bolsa_regiao <- bolsa %>%
  select(Ibge, `Qtd. beneficiários a serem acompanhados`, `Qtd. beneficiários acompanhados`)

bolsa_brasil <- bolsa %>%
  select(Estado, Município, Ibge, `Qtd. beneficiários a serem acompanhados`, `Qtd. beneficiários acompanhados`)
```

adicionando a informação de populacao por municipio

```{r}
bolsa_municipio <- merge(bolsa_municipio, populacao, by="Ibge")
bolsa_estado <- merge(bolsa_estado, populacao, by="Ibge")
bolsa_brasil <- merge(bolsa_brasil, populacao, by="Ibge")
bolsa_regiao <- merge(bolsa_regiao, populacao, by="Ibge")
```


# Por municipio



```{r}

bolsa_municipio %>% 
  ggplot(aes(x = `Perc. cobertura de beneficiários acompanhados (%)`)) +
  geom_histogram(fill = "steelblue") +
  labs(x = "Percentual de beneficiários acompanhados", y = "Quantidade", title = "Distribuição dos municipios por percentual de beneficiários acompanhados") +
  theme(plot.title = element_text(size = 12))

```






```{r}
dados <- bolsa_municipio %>%
  mutate(Proporcao = `Qtd. beneficiários acompanhados` / `Qtd. beneficiários a serem acompanhados`,
         Porcentagem = round(Proporcao * 100, 1)) %>%
  arrange(desc(Proporcao)) %>%
  slice_tail( n = 10)

indicador_global <- round(sum(bolsa_municipio$`Perc. cobertura de beneficiários acompanhados (%)`) / nrow(bolsa_municipio), 2) 

# Criando o gráfico
ggplot(dados, aes(x = reorder(Mun_uf, Proporcao), y = Proporcao, fill = Região)) +
  geom_col() +
  geom_text(aes(label = paste0(Porcentagem, "%")), vjust = 0.4) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(
    title = "Municípios com menos acompanhados",
    x = "Município",
    y = "Proporção de Acompanhamento"
  ) +
  theme_minimal() +
  geom_hline(
    yintercept = indicador_global,
    color      = "black",
    linetype   = "dashed",
    size       = 1
  ) +
  annotate(
    "text",
    x     = 1,
    y     = indicador_global,
    label = paste("Média Municipal: ", indicador_global * 100, "%"),
    hjust = 1, vjust = 0.5,
    color = "black"
  ) +
  theme(plot.title = element_text(size = 12)) +
  coord_flip()
```

# informações por UF

```{r}
bolsa_estado <- bolsa_estado %>%
  select(-Município)

prop_bsa_estado <- bolsa_estado %>%
  group_by(Estado) %>%
  summarise(sum_acomp = sum(`Qtd. beneficiários acompanhados`), sum_total_acomp = sum(`Qtd. beneficiários a serem acompanhados`), Proporcao = sum_acomp / sum_total_acomp)
```



```{r}
dados_grafico2 <- bolsa_estado %>%
  group_by(Estado, Região) %>%
  summarise(
    total_serem_acompanhados = sum(`Qtd. beneficiários a serem acompanhados`),
    total_populacao = sum(População),
    proporcao = total_serem_acompanhados / total_populacao
  ) %>%
  mutate(
    porcentagem = round(proporcao * 100, 1)
  ) %>%
  arrange(proporcao)  # Ordem crescente

indicador_global <- round(sum(dados_grafico2$proporcao) / nrow(dados_grafico2), 2) 

ggplot(dados_grafico2, aes(x = reorder(Estado, proporcao), y = proporcao, fill = Região)) +
  geom_col() +
  geom_text(aes(label = paste0(porcentagem, "%")), 
            hjust = -0.1, 
            color = "black", 
            size = 3.5) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                   expand = expansion(mult = c(0, 0.15))) +
  labs(title = "Beneficiários por UF",
       x = "UF",
       y = "Proporção de acompanhados") +
  geom_hline(
    yintercept = indicador_global,
    color      = "black",
    linetype   = "dashed",
    size       = 1
  ) +
  annotate(
    "text",
    x     = 1,
    y     = indicador_global,
    label = paste("Média por UF: ", indicador_global * 100, "%"),
    hjust = -0.3, vjust = 0.5,
    color = "black"
  ) +
  theme_minimal() +
  coord_flip()
```



```{r}
dados_grafico <- bolsa_estado %>%
  group_by(Estado, Região) %>%
  summarise(
    sum_acomp = sum(`Qtd. beneficiários acompanhados`),
    sum_total_acomp = sum(`Qtd. beneficiários a serem acompanhados`),
    Proporcao = sum_acomp / sum_total_acomp
  ) %>%
  mutate(
    Porcentagem = round(Proporcao * 100, 1),
    Estado = factor(Estado)
  )

# recalcula global
indicador_global <- round(sum(dados_grafico$Proporcao) / nrow(dados_grafico), 2) 

# Criando o gráfico
ggplot(dados_grafico, aes(x = reorder(Estado, Proporcao), y = Proporcao, fill = Região)) +
  geom_col() +
  geom_text(aes(label = paste0(Porcentagem, "%")), 
            hjust = 1.1, 
            color = "white", 
            size = 3,
            vjust = 0.4) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(
    title = "Acompanhados por UF",
    x = "UF",
    y = "Proporção de acompanhados"
  ) +
  geom_hline(
    yintercept = indicador_global,
    color      = "black",
    linetype   = "dashed",
    size       = 1
  ) +
  annotate(
    "text",
    x     = 1,
    y     = indicador_global,
    label = paste("Média por UF: ", indicador_global * 100, "%"),
    hjust = 0.4, vjust = 0.5,
    color = "black",
    size  = 3
  ) +
  theme_minimal() +
  coord_flip() 
```


# Por região




```{r}
dados_grafico2 <- bolsa_regiao %>%
  group_by(Região) %>%
  summarise(
    total_serem_acompanhados = sum(`Qtd. beneficiários a serem acompanhados`),
    total_populacao = sum(População),
    proporcao = total_serem_acompanhados / total_populacao
  ) %>%
  mutate(
    porcentagem = round(proporcao * 100, 1)
  ) %>%
  arrange(proporcao)  # Ordem crescente


media_regional <- round(sum(dados_grafico2$proporcao) / 5, 2)

ggplot(dados_grafico2, aes(x = reorder(Região, proporcao), y = proporcao, fill = Região)) +
  geom_col() +
  geom_text(aes(label = paste0(porcentagem, "%")), 
            hjust = -0.1, 
            color = "black", 
            size = 3.5) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                   expand = expansion(mult = c(0, 0.15))) +
  labs(title = "Beneficiários por Região",
       x = "Região",
       y = "Proporção de acompanhados") +
  geom_hline(aes(yintercept = media_regional),
             color    = "black",
             linetype = "dashed",
             size     = 1) +
  annotate("text", x = 0, y = media_regional,
           label = paste("Média por regiões: ", (media_regional) * 100, "%"),
           hjust = -0.5, vjust = -0.5, color = "black") +
  theme_minimal() +
  coord_flip() +
  guides(fill = "none")
```






```{r}

dados_grafico <- bolsa_regiao %>%
  group_by(Região) %>%
  summarise(
    sum_acomp = sum(`Qtd. beneficiários acompanhados`),
    sum_total_acomp = sum(`Qtd. beneficiários a serem acompanhados`),
    Proporcao = sum_acomp / sum_total_acomp
  ) %>%
  mutate(
    Porcentagem = round(Proporcao * 100, 1),
    Estado = factor(Região)
  )


media_regional <- dados_grafico %>%
  summarise(media = sum(Proporcao) / 5)

# Criando o gráfico
ggplot(dados_grafico, aes(x = reorder(Região, Proporcao), y = Proporcao, fill = Região)) +
  geom_col() +
  geom_text(aes(label = paste0(Porcentagem, "%")), 
            hjust = 1.1, 
            color = "white", 
            size = 3,
            vjust = 0.4) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(
    title = "Acompanhados por Região",
    x = "Região",
    y = "Proporção de acompanhados"
  ) +
  theme_minimal() +
  geom_hline(aes(yintercept = media_regional$media),
             color    = "black",
             linetype = "dashed",
             size     = 1) +
  annotate("text", x = 0, y = media_regional$media,
           label = paste("Média por regiões: ", round((media_regional$media) *100, 2)),
           hjust = 1.2, vjust = -0.5, color = "black") +
  coord_flip() +
  guides(fill = "none")
```



