---
title: "Promoção de praticas em saude"
author: "Erick Nasareth"
date: "2025-04-27"
output:
  html_document: default
  pdf_document: default
---

```{r echo =FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load("tidyverse", "readxl")
knitr::opts_chunk$set(echo = FALSE)
```



```{r}

#bolsa <- read_xlsx("Data/bolsa_familia_consolidado_geral_2023.xlsx")
populacao <- read_xls("Data/pop_cadastrada_2023.xls")
#atendimento <- read_xlsx("Data/atendimento_saude_2023.xlsx")
#palestras <- read_xlsx("Data/palestras_municipio_2023.xlsx") #temas
praticas <- read_xlsx("Data/praticas2023.xlsx")

```


```{r}

populacao <- rename(populacao, Ibge = IBGE)
praticas$Ibge <- as.double(praticas$Ibge)

```


```{r}

praticas$Antropometria <- gsub("\\.", "", praticas$Antropometria)
praticas$`Práticas corporais / atividade` <- gsub("\\.", "", praticas$`Práticas corporais / atividade`)
praticas$`Verificação da situação vacina` <- gsub("\\.", "", praticas$`Verificação da situação vacina`)

```


```{r}
praticas$Antropometria <- as.numeric(praticas$Antropometria)
praticas$`Práticas corporais / atividade` <- as.numeric(praticas$`Práticas corporais / atividade`)
praticas$`Verificação da situação vacina` <- as.numeric(praticas$`Verificação da situação vacina`)
```


```{r}
names(populacao)[7] <- "populacao_cadastrada"
```


```{r}
populacao <- populacao %>%
  select(Ibge, populacao_cadastrada, Região)

names(populacao)[2] <- "População"

populacao <- populacao %>%
  filter(População > 0)
```


```{r}
praticas_mun <- praticas %>%
  select(Ibge, Municipio, Antropometria, `Práticas corporais / atividade`, `Verificação da situação vacina`)

praticas_uf <- praticas %>%
  select(Ibge, Uf, Antropometria, `Práticas corporais / atividade`, `Verificação da situação vacina`)

praticas_regiao <- praticas %>%
  select(Ibge, Uf, Antropometria, `Práticas corporais / atividade`, `Verificação da situação vacina`)
```


```{r}

praticas_mun <- merge(praticas_mun, populacao, by="Ibge")
praticas_uf  <- merge(praticas_uf, populacao, by="Ibge")
praticas_regiao  <- merge(praticas_regiao, populacao, by="Ibge")
```


# Municipio

```{r}
# Calculando as taxas por 1.000 habitantes
dados_taxas_mun <- praticas_mun %>%
  summarise(
    Taxa_Antropometria = (Antropometria / População) * 100000,
    Taxa_Praticas = `Práticas corporais / atividade` / População * 100000,
    Taxa_Vacinacao = `Verificação da situação vacina` / População * 100000
  ) %>%
  ungroup()

dados_taxas_mun <- dados_taxas_mun %>%
  filter(Taxa_Vacinacao != 0, Taxa_Praticas != 0, Taxa_Antropometria != 0)
```

# Promoção de Práticas a cada 100.000 habitantes em municipios.

```{r}
dados_taxas_mun %>% 
  ggplot(aes(x = Taxa_Antropometria)) +
  geom_histogram(fill = "#76c893") +
  labs(title = "Práticas Antropométricas", x = "Práticas a cada 100.000 habitantes", y = "Quantidade de Municípios")
```


```{r}
dados_taxas_mun %>% 
  ggplot(aes(x = Taxa_Praticas)) +
  geom_histogram(fill = "#f67e7d") +
  labs(x = "Práticas a cada 100.000 habitantes", y = "Quantidade de Municípios", title = "Práticas Corporais")
```

```{r}
dados_taxas_mun %>% 
  ggplot(aes(x = Taxa_Vacinacao)) +
  geom_histogram(fill = "#c8b6ff") +
  labs(x = "Práticas a cada 100.000 habitantes", y = "Quantidade de municípios", title = "Praticas de Vacinação")
```


# UF 

```{r}
# Calculando as taxas por 100.000 habitantes
dados_taxas <- praticas_uf %>%
  group_by(Uf) %>%
  summarise(
    Taxa_Antropometria = sum(Antropometria) / sum(População) * 100000,
    Taxa_Praticas = sum(`Práticas corporais / atividade`) / sum(População) * 100000,
    Taxa_Vacinacao = sum(`Verificação da situação vacina`) / sum(População) * 100000
  ) %>%
  ungroup()
```



```{r}

media_global <- round(sum(dados_taxas$Taxa_Antropometria) / nrow(dados_taxas), 2)

ggplot(dados_taxas, aes(x = reorder(Uf, Taxa_Antropometria), y = Taxa_Antropometria)) +
  geom_bar(stat = "identity", fill = "#76c893") +
  geom_text(aes(label = sprintf("%.2f", round(Taxa_Antropometria, 2))), 
            vjust = 0.4, size = 3, color = "black") +
  labs(title = "Promoção de Práticas Antropométricas por 100.000 habitantes por UF",
       x = "UF",
       y = "Taxa por 100.000 hab.") +
  geom_hline(
    yintercept = media_global,
    color      = "black",
    linetype   = "dashed",
    size       = 1
  ) +
  annotate(
    "text",
    x     = 1,
    y     = media_global,
    label = paste("Média por UF: ", media_global),
    hjust = -0.5, vjust = 0.5,
    color = "black"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip()
```


```{r}
media_global <- round(sum(dados_taxas$Taxa_Praticas) / nrow(dados_taxas), 2)

ggplot(dados_taxas, aes(x = reorder(Uf, Taxa_Praticas), y = Taxa_Praticas)) +
  geom_bar(stat = "identity", fill = "#f67e7d") +
  geom_text(aes(label = sprintf("%.2f", round(Taxa_Praticas, 2))), 
            vjust = 0.4, size = 3, color = "black") +
  labs(title = "Promoção de Práticas Corporais por 100.000 habitantes por UF",
       x = "UF",
       y = "Taxa por 100.000 hab.") +
  geom_hline(
    yintercept = media_global,
    color      = "black",
    linetype   = "dashed",
    size       = 1
  ) +
  annotate(
    "text",
    x     = 1,
    y     = media_global,
    label = paste("Média por UF: ", media_global),
    hjust = -1, vjust = 0.1,
    color = "black"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip()
```


```{r}
media_global <- round(sum(dados_taxas$Taxa_Vacinacao) / nrow(dados_taxas), 2)


ggplot(dados_taxas, aes(x = reorder(Uf, Taxa_Vacinacao), y = Taxa_Vacinacao)) +
  geom_bar(stat = "identity", fill = "#c8b6ff") +
  geom_text(aes(label = sprintf("%.2f", round(Taxa_Vacinacao, 2))), 
            vjust = 0.4, size = 3, color = "black") +
  labs(title = "Promoção de Atividades Vacinais por 100.000 habitantes por UF",
       x = "UF",
       y = "Taxa por 100.000 hab.") +
  geom_hline(
    yintercept = media_global,
    color      = "black",
    linetype   = "dashed",
    size       = 1
  ) +
  annotate(
    "text",
    x     = 1,
    y     = media_global,
    label = paste("Média por UF: ", media_global),
    hjust = -1, vjust = 0.5,
    color = "black"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip()
```


# Promoção de Práticas ... a cada 100.000 habitantes por região



```{r}
# Calculando as taxas por 100.000 habitantes
dados_taxas_regiao <- praticas_uf %>%
  group_by(Região) %>%
  summarise(
    Taxa_Antropometria = sum(Antropometria) / sum(População) * 100000,
    Taxa_Praticas = sum(`Práticas corporais / atividade`) / sum(População) * 100000,
    Taxa_Vacinacao = sum(`Verificação da situação vacina`) / sum(População) * 100000
  ) %>%
  ungroup()
```


```{r}
media_global <- round(sum(dados_taxas_regiao$Taxa_Antropometria) / nrow(dados_taxas_regiao), 2)

ggplot(dados_taxas_regiao, aes(x = reorder(Região, Taxa_Antropometria), y = Taxa_Antropometria)) +
  geom_bar(stat = "identity", fill = "#76c893") +
  geom_text(aes(label = sprintf("%.2f", round(Taxa_Antropometria, 2))), 
            vjust = 0.4, size = 3, color = "black") +
  labs(title = "Praticas em Antropometria",
       x = "Região",
       y = "Taxa por 100.000 hab.") +
  geom_hline(
    yintercept = media_global,
    color      = "black",
    linetype   = "dashed",
    size       = 1
  ) +
  annotate(
    "text",
    x     = 1,
    y     = media_global,
    label = paste("Média por Região: ", media_global),
    hjust = -0.1, vjust = 0.5,
    color = "black"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip()
```


```{r}
media_global <- round(sum(dados_taxas_regiao$Taxa_Praticas) / nrow(dados_taxas_regiao), 2)

ggplot(dados_taxas_regiao, aes(x = reorder(Região, Taxa_Praticas), y = Taxa_Praticas)) +
  geom_bar(stat = "identity", fill = "#f67e7d") +
  geom_text(aes(label = sprintf("%.2f", round(Taxa_Praticas, 2))), 
            vjust = 0.4, size = 3, color = "black") +
  labs(title = "Práticas Corporais",
       x = "Região",
       y = "Taxa por 100.000 hab.") +
  geom_hline(
    yintercept = media_global,
    color      = "black",
    linetype   = "dashed",
    size       = 1
  ) +
  annotate(
    "text",
    x     = 1,
    y     = media_global,
    label = paste("Média por Região: ", media_global),
    hjust = 0.5, vjust = 0.5,
    color = "black"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip()
```


```{r}
media_global <- round(sum(dados_taxas_regiao$Taxa_Vacinacao) / nrow(dados_taxas_regiao), 2)

ggplot(dados_taxas_regiao, aes(x = reorder(Região, Taxa_Vacinacao), y = Taxa_Vacinacao)) +
  geom_bar(stat = "identity", fill = "#c8b6ff") +
  geom_text(aes(label = sprintf("%.2f", round(Taxa_Vacinacao, 2))), 
            vjust = 0.4, size = 3, color = "black") +
  labs(title = "Atividades vacinais",
       x = "Região",
       y = "Taxa por 100.000 hab.") +
  geom_hline(
    yintercept = media_global,
    color      = "black",
    linetype   = "dashed",
    size       = 1
  ) +
  annotate(
    "text",
    x     = 1,
    y     = media_global,
    label = paste("Média por Região: ", media_global),
    hjust = -0.5, vjust = 0.5,
    color = "black"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip()
```


